name: Analyze, Test and Build

on:
  push:
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'

jobs:
  build:
    name: Analyze, Test and Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Clone flutter repository from stable channel with the latest version
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Test code
        run: flutter test

      - name: Build code
        run: flutter config --enable-windows-desktop && flutter build windows
